execute_process(RESULT_VARIABLE res COMMAND ${CMAKE_ARGV3} -c ${CMAKE_ARGV4} -o ${CMAKE_ARGV5})
if(NOT(${res} EQUAL 0))
  if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.29") 
    cmake_language(EXIT 1)
  else()
    message(FATAL_ERROR)
  endif()
endif()
execute_process(RESULT_VARIABLE res COMMAND ${CMAKE_ARGV6} ${CMAKE_ARGV5} ${CMAKE_ARGV7})
if(NOT(${res} EQUAL 0))
  if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.29") 
    cmake_language(EXIT 1)
  else()
    message(FATAL_ERROR)
  endif()
endif()