execute_process(OUTPUT_VARIABLE out RESULT_VARIABLE res COMMAND ${CMAKE_ARGV3} -c ${CMAKE_ARGV4} -o ${CMAKE_ARGV5})
if(NOT(${res} EQUAL 0))
  message(FATAL_ERROR ${out})
endif()
execute_process(ECHO_OUTPUT_VARIABLE RESULT_VARIABLE res COMMAND ${CMAKE_ARGV6} ${CMAKE_ARGV5} ${CMAKE_ARGV7})
if(NOT(${res} EQUAL 0))
  message(FATAL_ERROR ${out})
endif()