= Change log
:toc:
:toc-title:

== 3.0.0 (in progress)
=== Frontend (user-facing)
==== Features
* Removed all 2.0.0 features, restarting from scratch.
* Added support for using `compile_commands.json` to provide modularizing context for files.
* Added a `[bootstrap]` fallback mode for projects without JSON compilation database.

==== Distribution
* Official supported OS'es and architectures
* Official distribution mean and format

=== Backend (developer-facing)
* Official supported build toolchain (LLVM)
* Offical directory-based format for tests
* Directly intergrated C{plus}{plus} test driver to replace the old CMake-based one
* AsciiDoc instead of Markdown for documentation

==== Library changes
|===
|Area |2.0.0 |3.0.0 |Reason

|Core logic
|https://pcre2project.github.io/pcre2[PCRE2]
|https://clang.llvm.org/docs/LibTooling.html[LibTooling]
|Regex is just pattern matching, it can't understand C{plus}{plus} syntax.

|CLI
|https://github.com/Taywee/args[Taywee/args]
|https://llvm.org/docs/CommandLine.html[LLVM CommandLine]
|Already using LLVM, might as well use more of it.

|Logging
|https://github.com/fmtlib/fmt[{fmt}]
|https://llvm.org/doxygen/classllvm_1_1raw__ostream.html[LLVM streams]
|Already using LLVM, might as well use more of it.

|TOML
|https://github.com/marzer/tomlplusplus[marzer/toml{plus}{plus}]
|https://github.com/cktan/tomlc17[cktan/tomlc17]
|Only need parsing, so the more minimal the better.
|===

== 2.0.0
=== Breaking changes
* Renamed `includeGuardPat` to `includeGuard`.
* Changed TOML transitional mode to `[transitional]` (was `[Transitional]`) to match the
command-line & project naming conventions.
* Updated default for `moduleInterfaceExt` to `ixx` (was `cppm`) for MSVC compatibility.
* Removed the `logCurrentFile` setting; importizer now automatically logs the current file being
processed on errors.

==== Off-by-default rule
* Include guards & `#pragma once` are no longer processed by default.
* Introduced a new `pragmaOnce` setting to control `#pragma once` handling.

=== Features
* `SOFComments` setting for handling start-of-file comments (e.g., license headers).
* Minimizer can now remove empty `#el...` statements.

=== Changes & fixes
* Separated the IncludePrevention test into distinct tests for include guards & `#pragma once`.
Eliminated condition generation for local includes in transitional mode.
* Updated documentation for the `includeGuard` setting.
* Renamed the "`Other`" test to "`ModeIndependent`".
* Classified Minimizer & umbrella header tests as ModeIndependent.
* Made CMake precompiled headers optional (opt-in via `PCH`).
* Change the argument parser from https://github.com/p-ranav/argparse[p-ranav/argparse] to
https://github.com/Taywee/args[Taywee/args] to avoid `std::any` issues on Windows Clang #13.

== 1.1.0
* Added a shared directive section in transitional mode to shorten the preamble.
* Added support for umbrella headers by converting includes to `export import` instead of plain
`import`.
* Bump PCRE2 to 10.45.

== 1.0.1
* Fixed `includeGuardPat` to match the entire string required for a guard.
* Corrected `CondMinimizer` to skip only skippable `#if` statements rather than all of them.
* Resolved an issue with raw string handling where the first `(` was not properly skipped.
* Fixed the handling of integer literals.
* Improved `CondMinimizer` to correctly handle nested `#if` directives (it previously looked for the
earliest `#endif`).
* Simplified the condition hierarchy by removing conditions for all imports.
* Updated dependencies: bumped libfmt to 11.1.3, PCRE2 to 10.45-RC1, and Argparse to 3.2.

== 1.0.0
First Release
