# ClangBuildAnalyzer reads ClangBuildAnalyzer.ini file from the working directory
# when invoked, and various aspects of reporting can be configured this way.

# How many of most expensive things are reported?
[counts]

# files that took most time to parse
fileParse = 0

# files that took most time to generate code for
fileCodegen = 0

# functions that took most time to generate code for
function = 0

# header files that were most expensive to include
header = 15

# for each expensive header, this many include paths to it are shown
headerChain = 10

# templates that took longest to instantiate
template = 0


# Minimum times (in ms) for things to be recorded into trace
[minTimes]

# parse/codegen for a file
file = 1


[misc]

# Maximum length of symbol names printed; longer names will get truncated
maxNameLength = 100

# Only print "root" headers in expensive header report, i.e.
# only headers that are directly included by at least one source file
onlyRootHeaders = false
