if(LINUX)
  set(CMAKE_C_COMPILER "clang")
  set(CMAKE_CXX_COMPILER "clang++")
  set(CMAKE_LINKER_TYPE "LLD")
  set(CMAKE_CXX_COMPILER_RANLIB "ranlib")
  set(CMAKE_CXX_COMPILER_AR "ar")
elseif(APPLE)
  set(CMAKE_C_COMPILER "clang")
  set(CMAKE_CXX_COMPILER "clang++")
  set(CMAKE_OSX_DEPLOYMENT_TARGET "15")
elseif(WIN32)
  set(CMAKE_C_COMPILER "clang-cl")
  set(CMAKE_CXX_COMPILER "clang-cl")
  set(CMAKE_LINKER_TYPE "LLD")
  set(CMAKE_ASM_MASM_COMPILER "llvm-ml")
  set(CMAKE_ASM_MASM_FLAGS "-m64")
endif()
