function(ckRes res_)
  if(NOT ${res_} EQUAL 0)
    cmake_language(EXIT 1)
  endif()
endfunction()
execute_process(RESULT_VARIABLE res COMMAND ${IMPORTIZER} ${CONFIG} -o ${OUT_DIR})
ckRes(res)
execute_process(RESULT_VARIABLE res COMMAND ${CMP_DIR} ${OUT_DIR} ${CORRECT})
ckRes(res)
