function(ckRes res_)
  if(NOT ${res_} EQUAL 0)
    cmake_language(EXIT 1)
  endif()
endfunction()
set(importizer ${CMAKE_ARGV3})
set(config ${CMAKE_ARGV4})
set(outDir ${CMAKE_ARGV5})
set(cmpDir ${CMAKE_ARGV6})
set(correctOutput ${CMAKE_ARGV7})
execute_process(RESULT_VARIABLE res COMMAND ${importizer} ${config} -o ${outDir})
ckRes(res)
execute_process(RESULT_VARIABLE res COMMAND ${cmpDir} ${outDir} ${correctOutput})
ckRes(res)
