name: Build, test and pack
inputs:
  mode:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        # Configure
        cmake -B build -DCMAKE_BUILD_mode=${{ inputs.mode }} --preset ci -DCPACK_PACKAGE_FILE_NAME=importizer-${{ matrix.os }}-${{ matrix.arch }}

        # Build
        cmake --build build --config ${{ inputs.mode }} -j $(cmake -P scripts/Nproc.cmake)

        # Test
        ctest --test-dir build/tests -C ${{ inputs.mode }} --output-on-failure --progress --schedule-random -j $(cmake -P scripts/Nproc.cmake)

        # Pack
        cpack --config build/CPackConfig.cmake -C ${{ inputs.mode }} -DCPACK_THREADS=$(cmake -P scripts/Nproc.cmake)
