name: Make Alpine Images
on: workflow_dispatch
jobs:
  jobMatrix:
    uses: ./.github/workflows/JobMatrix.yml
    with:
      jqExpr: 'del(.[] | select(.os != "linux"))'
  make:
    needs: jobMatrix
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.jobMatrix.outputs.m) }}
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.arch }}
    steps:
      - name: all
        run: |
          repo=${{ github.repository }}

          podman build \
            https://raw.githubusercontent.com/$repo/${{ github.sha }}/scripts/alpine/Containerfile \
            --platform linux/${{ matrix.arch }} \
            -t img

          podman login ghcr.io \
            -u msqr1 \
            -p ${{ github.token }}

          podman push img \
            ghcr.io/${{ github.repository }}-alpine:3.24.0-${{ matrix.arch }} \
            -f oci \
            --compression-format zstd \
            --compression-level 19

          podman logout --all
