name: Cache to Release
on:
  - workflow_dispatch
jobs:
  jobMatrix:
    uses: ./.github/workflows/JobMatrix.yml
  all:
    permissions:
      contents: write
    needs: jobMatrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.jobMatrix.outputs.m) }}
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - name: Check cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.5
        with:
          path: |
            3rd-party/llvm
            3rd-party/clang
          key: Libtooling-22.1.6-${{ matrix.os }}-${{ matrix.arch }}
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Setup
          . scripts/setup-env/${{ matrix.script }} ${{ matrix.arch }}

          # Ensure LibTooling
          cmake -P scripts/EnsureLibtooling.cmake
