name: Tag Release
on:
  - workflow_dispatch
jobs:
  jobMatrix:
    uses: ./.github/workflows/JobMatrix.yml
    with:
      checkCi: true
  all:
    permissions:
      contents: write
    needs: jobMatrix
    strategy:
      matrix:
        include: ${{ fromJSON(needs.jobMatrix.outputs.m) }}
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@v1.4.2
      - name: All
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Setup
          . scripts/setup-env/${{ matrix.script }} ${{ matrix.arch }}

          # Ensure LibTooling
          cmake -P scripts/EnsureLibtooling.cmake

          # Make distribution
          cmake -P scripts/MkDist.cmake Release
      - name: Upload binary as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ matrix.os }}-${{ matrix.arch }}.zst
          retention-days: 1
          compression-level: 0
          if-no-files-found: error
  tagRelease:
    permissions:
      contents: write
      repository-projects: write
    needs: all
    runs-on: ubuntu-slim
    steps:
      - name: Download distributions
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
        with:
          merge-multiple: true
          path: dists
      - name: Enable release immutability
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/${{ github.repository }}/immutable-releases \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10"
      - name: Create & upload to release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # 3.0.0
        with:
          tag_name: 3.0.0
          body: "[Change log](https://github.com/msqr1/importizer/blob/main/ChangeLog.adoc#300)"
          files: dists/*
      - name: Disable release immutability
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/${{ github.repository }}/immutable-releases \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10"
