name: Run test and tag continuous
on:
  - push
  - workflow_dispatch
permissions:
  contents: write
jobs:
  build-test-upload:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - windows-latest
          - macos-26
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build
        id: build
        run: >
          mkdir build && cd build && cmake .. -DTESTS=1 -DCMAKE_BUILD_TYPE=Debug &&
          cmake --build . --config Debug -j $(cmake -P ${{ github.workspace }}/nproc.cmake)
      - name: Test
        id: test
        if: steps.build.outcome == 'success'
        run: >
          cd ${{ github.workspace }}/build/test &&
          ctest -C Debug --output-on-failure --progress --schedule-random
          -j $(cmake -P ${{ github.workspace }}/nproc.cmake)
      - name: Upload built executable as artifact
        id: upload
        if: steps.test.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: importizer-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/build/importizer
            ${{ github.workspace }}/build/importizer.exe
          retention-days: 1
          compression-level: 0

  download-and-release-continuous:
    needs: build-test-upload
    runs-on: ubuntu-slim
    steps:
      - name: Download built executables
        uses: actions/download-artifact@v8
      - name: Rename executables
        run: |
          for exe in */importizer*; do
            platform=$(dirname $exe)
            filename=$(basename $exe)
            mv $exe "$platform/$platform$([[ $filename = *.* ]] && echo .${filename##*.} || echo '')"
          done
      - name: Tag continuous release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          tag_name: continuous
          body: Latest test-passing unstable release. Select your OS, download and try it
            out!
          files: ${{ github.workspace }}/importizer*/importizer*
