name: Run test and tag continuous
on:
  - push
  - workflow_dispatch
permissions:
  contents: write
jobs:
  build-test-upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux
            script-ext: "sh"
          - os: windows-latest
            name: windows
            script-ext: "ps1"
          - os: macos-14
            name: macos
            script-ext: "sh"
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup
        run: scripts/SetupCI-${{ matrix.name }}.${{ matrix.script-ext }}
      - name: Build
        id: build
        run: >
          mkdir build && cd build &&
          cmake .. --preset gh-${{ matrix.name }} -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Debug -DCUSTOM_EXE_SUFFIX=${{ matrix.name }} &&
          cmake --build . --config Debug -j $(cmake -P ${{ github.workspace }}/scripts/Nproc.cmake)
      - name: Test
        id: test
        if: steps.build.outcome == 'success'
        run: >
          cd ${{ github.workspace }}/build/tests &&
          ctest -C Debug --output-on-failure --progress --schedule-random
          -j $(cmake -P ${{ github.workspace }}/scripts/Nproc.cmake)
      - name: Upload executable as artifact
        id: upload
        if: steps.test.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ github.workspace }}/build/importizer-${{ matrix.name }}
            ${{ github.workspace }}/build/importizer-${{ matrix.name }}.exe
          retention-days: 1
          compression-level: 0

  download-tag-continuous:
    needs: build-test-upload
    runs-on: ubuntu-slim
    steps:
      - name: Download executables
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: executables
      - name: Tag continuous release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          tag_name: continuous
          body: Latest test-passing debug release. Select your OS, download and try it
            out!
          files: executables/*
