name: Tag Continuous
on:
  - push
  - workflow_dispatch
jobs:
  jobMatrix:
    uses: ./.github/workflows/JobMatrix.yml
    with:
      jqExpr: 'map(select(.os != "macos"))'
  all:
    permissions:
      contents: write
    needs: jobMatrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.jobMatrix.outputs.m) }}
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.os }}-${{ matrix.arch }}
    container: ${{ matrix.container || '' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@v1.4.2
      - name: Setup environment
        run: . scripts/setup-env/${{ matrix.setup-env }} ${{ matrix.arch }}
      - name: Ensure LibTooling
        timeout-minutes: 167
        run: cmake -P scripts/EnsureLibtooling.cmake
      - name: Make & upload distribution
        timeout-minutes: 5
        run: cmake -P scripts/MkDist.cmake Debug
