name: Tag continuous
on:
  - push
permissions:
  contents: write
jobs:
  job-matrix:
    uses: ./.github/workflows/JobMatrix.yml
  make-dist:
    needs: job-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.job-matrix.outputs.m) }}
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - name: Setup
        run: . ./scripts/setup-env/${{ matrix.script }} ${{ matrix.arch }}
      - name: Ensure LibTooling
        uses: ./.github/actions/ensure-libtooling
        with:
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          script: ${{ matrix.script }}
          shell: ${{ matrix.shell }}
      - name: Build (debug), test, pack
        shell: bash
        run: ./scripts/BuildTestPack.sh Debug ${{ matrix.os }} ${{ matrix.arch }}
      - name: Upload
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # 3.0.0
        with:
          prerelease: true
          tag_name: continuous
          target_commitish: ${{ github.sha }}
          files: importizer-${{ matrix.os }}-${{ matrix.arch }}.${{ matrix.outExt }}
          fail_on_unmatched_files: true
