name: Job Matrix
on:
  workflow_call:
    inputs:
      checkCi:
        description: Check CI status of HEAD
        type: boolean
        default: false
      jqExpr:
        description: jq filter expression for jobs
        type: string
        default: ""
    outputs:
      m:
        description: Job matrix
        value: ${{ jobs.all.outputs.m }}
jobs:
  all:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    outputs:
      m: ${{ steps.all.outputs.m }}
    steps:
      - id: all
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          repo=repos/${{ github.repository }}
          sha=${{ github.sha }}

          ${{ inputs.checkCi }} &&
          "$(gh api $repo/actions/workflows/Ci.yml/runs?head_sha=$sha \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            -q '(.total_count > 0 and .workflow_runs[0].conclusion != "success")')" &&
          exit 1

          echo "m=$(gh api $repo/contents/CiMatrix.json \
            -H "Accept: application/vnd.github.raw+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            -q '${{ inputs.jqExpr }}')" >> "$GITHUB_OUTPUT"
