name: Job Matrix
on:
  workflow_call:
    inputs:
      check-prev:
        description: Check build status of latest commit
        type: boolean
        default: false
    outputs:
      m:
        description: "Job matrix"
        value: ${{ jobs.all.outputs.m }}
jobs:
  all:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    outputs:
      m: ${{ steps.get.outputs.m }}
    steps:
      - if: inputs.check-prev == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
      - id: get
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "m=$(gh api repos/${{ github.repository }}/contents/CiMatrix.json \
            -H "Accept: application/vnd.github.raw+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            | jq -c 'del(.[] | select(.os == "linux"))')" >> $GITHUB_OUTPUT
