name: Tag release
on:
  - workflow_dispatch

permissions:
  contents: write

jobs:
  job-matrix:
    uses: ./.github/workflows/JobMatrix.yml
  make-dist:
    needs: job-matrix
    strategy:
      matrix:
        include: ${{ fromJSON(needs.job-matrix.outputs.m) }}
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup, build (release), test, pack
        id: all
        run: |
          # Setup
          . ./scripts/setup/${{ matrix.setup }}

          # Configure
          cmake -B build -DCMAKE_BUILD_TYPE=Debug --preset ci-${{ matrix.os }} \
            -DCPACK_PACKAGE_FILE_NAME=importizer-${{ matrix.os }}-${{ matrix.arch }}

          # Build
          cmake --build build --config Release -j $(cmake -P scripts/Nproc.cmake)

          # Test
          ctest --test-dir build/tests -C Release --output-on-failure --progress \
            --schedule-random -j $(cmake -P scripts/Nproc.cmake)

          # Pack
          cpack --config build/CPackConfig.cmake -C Release \
            -DCPACK_THREADS=$(cmake -P scripts/Nproc.cmake)
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: ${{ github.workspace }}/importizer-${{ matrix.os }}-${{ matrix.arch }}.${{ matrix.outExt }}
          retention-days: 1
          compression-level: 0
          if-no-files-found: error
  tag-release:
    needs: make-dist
    runs-on: ubuntu-slim
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: dists
      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: 3.0.0
          body: "[Change log](https://github.com/msqr1/importizer/blob/main/ChangeLog.asc#300)"
          files: dists/*
