name: Run test and tag continuous
on:
  - push
  - workflow_dispatch
permissions:
  contents: write
jobs:
  build-upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux
            # Ubuntu 22.04 doesn't have LLVM 20
            cmd: >
              wget https://apt.llvm.org/llvm.sh
              chmod +x llvm.sh
              sudo ./llvm.sh 20
          - os: windows-latest
            name: windows
            # MacOS does have LLVM 20, but it need a bit of tweak
          - os: macos-26
            name: macos
            cmd: ln -s $(brew --prefix)/etc/clang ~/.config/clang
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup command
        run: ${{ matrix.cmd }}
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build
        id: build
        run: >
          mkdir build && cd build &&
          cmake .. --preset gh-${{ matrix.name }} -DCMAKE_BUILD_TYPE=Release -DCUSTOM_EXE_SUFFIX=${{ matrix.name }} &&
          cmake --build . --config Ninja -j $(cmake -P ${{ github.workspace }}/nproc.cmake)
      - name: Upload executable as artifact
        id: upload
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ github.workspace }}/build/importizer-${{ matrix.name }}
            ${{ github.workspace }}/build/importizer-${{ matrix.name }}.exe
          retention-days: 1
          compression-level: 0

  download-tag-release:
    needs: build-upload
    runs-on: ubuntu-slim
    steps:
      - name: Download built executables
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: executables
      - name: Upload to tag
        uses: softprops/action-gh-release@v3
        with:
          tag_name: 2.0.0
          body: "[Change log](https://github.com/msqr1/importizer/blob/main/ChangeLog.md#200)"
          files: executables/*
