name: Tag release
on:
  - workflow_dispatch
permissions:
  contents: write
jobs:
  build-pack-upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux
            script-ext: "sh"
          - os: windows-latest
            name: windows
            script-ext: "ps1"
          - os: macos-14
            name: macos
            script-ext: "sh"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup
        run: scripts/SetupCI-${{ matrix.name }}.${{ matrix.script-ext }}
      - name: Build
        id: build
        run: >
          mkdir build && cd build &&
          cmake .. --preset gh-${{ matrix.name }} -DCMAKE_BUILD_TYPE=Release &&
          cmake --build . --config Ninja -j $(cmake -P ${{ github.workspace }}/nproc.cmake)
      - name: Pack
        if: steps.test.outcome == 'success'
        id: pack
        run: >
          cd ${{ github.workspace }}/build &&
          cpack -C Debug -DCPACK_PACKAGE_FILE_NAME=importizer-${{ matrix.name }}
      - name: Upload
        if: steps.pack.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ github.workspace }}/build/importizer-${{ matrix.name }}.tar.gz
            ${{ github.workspace }}/build/importizer-${{ matrix.name }}.zip
          retention-days: 1
          compression-level: 0

  download-tag-release:
    needs: build-pack-upload
    runs-on: ubuntu-slim
    steps:
      - name: Download built executables
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: executables
      - name: Upload to tag
        uses: softprops/action-gh-release@v3
        with:
          tag_name: 2.0.0
          body: "[Change log](https://github.com/msqr1/importizer/blob/main/ChangeLog.md#200)"
          files: executables/*
