name: Tag release
on:
  - workflow_dispatch
permissions:
  contents: write
defaults:
  run:
    shell: bash
jobs:
  build-pack-upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux
            archive-ext: "tar.gz"
          - os: windows-latest
            name: windows
            archive-ext: "zip"
          - os: macos-14
            name: macos
            archive-ext: "tar.gz"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup
        run: scripts/SetupCI-${{ matrix.name }}.sh
      - name: Build
        id: build
        run: |
          cmake -B build \
            --preset ci-${{ matrix.name }} \
            -DBUILD_TESTING=1 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCPACK_PACKAGE_FILE_NAME=importizer-${{ matrix.name }}
          cmake --build build \
            --config Release \
            -j $(cmake -P ${{ github.workspace }}/scripts/Nproc.cmake)
      - name: Pack
        id: pack
        run: |
          cd ${{ github.workspace }}/build
          cpack -C Release
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: ${{ github.workspace }}/build/importizer-${{ matrix.name }}.${{ matrix.archive-ext }}
          retention-days: 1
          compression-level: 0
          if-no-files-found: error
  download-tag-release:
    needs: build-pack-upload
    runs-on: ubuntu-slim
    steps:
      - name: Count distributions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          n_dist=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            -q ".total_count")
          if [ "$n_dist" -lt 3 ]; then
            exit 1
          fi
      - name: Download distributions
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: dists
      - name: Upload to tag
        uses: softprops/action-gh-release@v3
        with:
          tag_name: 2.0.0
          body: "[Change log](https://github.com/msqr1/importizer/blob/main/ChangeLog.md#200)"
          files: dists/*
