name: Run test and upload to the latest release
on:
  - workflow_dispatch
permissions:
  contents: write
jobs:
  build-upload-test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2019
          - windows-2022
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Build
        id: build
        run: >
          mkdir build && cd build && cmake .. -DTESTS=1 -DCMAKE_BUILD_TYPE=Release &&
          cmake --build . --config Release
          -j $(cmake -P ${{ github.workspace }}/nproc.cmake)
      - name: Upload built executable as artifact
        id: upload
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4.6.0
        with:
          name: importizer-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/build/importizer
            ${{ github.workspace }}/build/importizer.exe
          retention-days: 1
          compression-level: 0
      - name: Test
        if: steps.upload.outcome == 'success'
        id: test
        run: >
          cd ${{ github.workspace }}/build/test &&
          ctest --output-on-failure -C Release --progress
          -j $(cmake -P ${{ github.workspace }}/nproc.cmake)
  download-and-release-continuous:
    needs: build-upload-test
    runs-on: ubuntu-24.04
    steps:
      - name: Download built executables
        uses: actions/download-artifact@v4.1.8
      - name: Rename executables
        run: |
          for exe in */importizer*; do
            platform=$(dirname $exe)
            filename=$(basename $exe)
            mv $exe "$platform/$platform$([[ $filename = *.* ]] && echo .${filename##*.} || echo '')"
          done
      - name: Upload to tag
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: 1.0.1
          body: "[Change log](https://github.com/msqr1/importizer/blob/main/ChangeLog.md#101)"
          files: ${{ github.workspace }}/importizer*/importizer*